"""What a tool hands back, and what is deliberately left out.

Every tool returns a model from this file, for one concrete reason: FastMCP
publishes a pydantic return type as the tool's `outputSchema`, so a host knows
the shape of a result before it calls -- and a host that knows the shape asks
for the right thing instead of calling twice to find out.

The models are **projections, not mirrors**. The API's own wire types are in
`contract_analyzer/api/schemas.py` and they are right for a browser: a
`ComplianceResult` carries `confidence_components`, `structure_rounds`,
`unresolved_errors`, `usage`, `ended_by` -- fields a KPI page plots and a
reviewer reads. Every one of them is a token in a model's context window, and
none of them changes what the host says next. So this file keeps the verdict,
the confidence, the flag that says a human should look, and -- only when asked
-- the quotes and the reasoning.

The other rule is that **nothing here is generated by us**. Compliance states,
quotes and confidences are the analyzer's, copied across; the only strings this
file writes are `next_step`, which describes the protocol rather than the
contract. A connector that summarised a report in its own words would be a
second, unlogged analysis of it.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

#: Statuses that will never change again. Everything else is worth polling.
TERMINAL = ("done", "failed", "cancelled", "interrupted")


# --------------------------------------------------------------------------
# Orientation
# --------------------------------------------------------------------------


class Started(BaseModel):
    """`get_started`: what this deployment can do right now.

    Live state rather than a README, because every field here is one that
    turns a confident tool call into a failure: no answer key means analysis
    is refused, no documents means there is no `document_id` to pass, and a
    number of analyses already running is the difference between "this is
    slow" and "this is stuck".
    """

    api_url: str
    version: str = ""
    #: False when ANTHROPIC_API_KEY is unset: upload and search still work,
    #: analysis does not. Say so rather than starting a run that will 503.
    key_present: bool = False
    #: Whether the API demands an X-API-Key. When true and this connector has
    #: none, every call except this one fails with `unauthorized`.
    auth_required: bool = False
    #: True when this connector is sending a key. The pair is what makes an
    #: auth failure diagnosable from one tool call.
    key_configured: bool = False
    analysis_model: str = ""
    retrieval_mode: str = ""
    documents: int = 0
    analyses_running: int = 0
    criteria: int = 0
    #: One sentence naming the tool to call next, given the state above.
    next_step: str = ""


class SubRequirement(BaseModel):
    id: str
    requirement: str


class Criterion(BaseModel):
    """One of the five questions, with the parts a verdict is built from."""

    id: str
    requirement: str
    question: str
    sub_requirements: list[SubRequirement] = Field(default_factory=list)
    states: list[str] = Field(default_factory=list)


# --------------------------------------------------------------------------
# Contracts
# --------------------------------------------------------------------------


class LastAnalysis(BaseModel):
    """The newest run against a contract, so a host can offer to read it
    instead of paying for a second one."""

    analysis_id: str
    status: str
    completed_at: str | None = None
    #: `{"Fully Compliant": 3, "Partially Compliant": 2}` -- counts, not a
    #: sentence. The host writes the sentence.
    states: dict[str, int] = Field(default_factory=dict)
    needs_review: int = 0


class Contract(BaseModel):
    document_id: int
    filename: str
    pages: int | None = None
    chunks: int = 0
    ingested_at: str = ""
    last_analysis: LastAnalysis | None = None


class Uploaded(BaseModel):
    """`upload_contract`: the id everything else needs.

    `note` is not decoration. Each upload mints a new `document_id` even for
    identical bytes -- that is what keeps two sessions working on the same
    contract from seeing each other's analyses -- and a host that assumes
    "same file, same id" will hand back an id from an earlier conversation.
    """

    document_id: int
    filename: str
    pages: int | None = None
    chunks: int = 0
    elapsed_s: float = 0.0
    note: str = ""


# --------------------------------------------------------------------------
# Analyses
# --------------------------------------------------------------------------


class AnalysisStarted(BaseModel):
    """`analyze_compliance`: a handle and a waiting instruction.

    The run is 60-180 s and this returns in under one. `poll_after_seconds`
    exists because a host left to its own instincts either asks twice a second
    or asks once, sees `running`, and tells the user it failed.
    """

    analysis_id: str
    document_id: int
    status: str
    criteria: list[str] = Field(default_factory=list)
    poll_after_seconds: float = 10.0
    next_step: str = ""


class CriterionProgress(BaseModel):
    """One row of the progress table: where a criterion got to, and what it
    concluded if it got there."""

    id: str
    status: str = "queued"
    state: str | None = None
    confidence: float | None = None
    needs_review: bool | None = None


class Quote(BaseModel):
    """A clause from the contract, with what a reviewer needs to find it.

    `verified` is a real check, not a formality: the quote was extracted by the
    model API from a passage we sent, and this says whether it was still found
    verbatim in that passage afterwards. A host presenting an unverified quote
    as the contract's words is presenting something nobody has confirmed.
    """

    text: str
    section_ref: str = ""
    page_display: str = ""
    chunk_id: int | None = None
    verified: bool = True


class Verdict(BaseModel):
    """One criterion's answer. `rationale` and `quotes` only at `detail="full"`."""

    criterion_id: str
    question: str = ""
    state: str = ""
    confidence: float = 0.0
    needs_review: bool = False
    sub_requirements: dict[str, str] = Field(
        default_factory=dict,
        description="Sub-requirement id to met / partially_met / not_met / not_addressed.",
    )
    rationale: str = ""
    quotes: list[Quote] = Field(default_factory=list)


class AnalysisState(BaseModel):
    """`get_analysis`: where the run is, and its verdicts once there are any.

    `retry_after_seconds` is set while the run is unfinished and `null` once it
    is terminal, so "should I ask again" is a field rather than an inference
    from a status string the host has to know the vocabulary of.
    """

    analysis_id: str
    document_id: int
    status: str
    stage: str = ""
    done: int = 0
    total: int = 0
    criteria: list[CriterionProgress] = Field(default_factory=list)
    #: Counts per compliance state over the finished criteria.
    states: dict[str, int] = Field(default_factory=dict)
    needs_review: int = 0
    mean_confidence: float = 0.0
    cost_usd: float = 0.0
    latency_s: float = 0.0
    #: Present once the run has produced results. Empty while it is queued.
    verdicts: list[Verdict] = Field(default_factory=list)
    #: Criteria that never ran, because the analysis was cancelled.
    skipped: list[str] = Field(default_factory=list)
    error: str | None = None
    #: The id every log line of this run carries.
    trace_id: str | None = None
    retry_after_seconds: float | None = None
    next_step: str = ""


# --------------------------------------------------------------------------
# Retrieval
# --------------------------------------------------------------------------


class Passage(BaseModel):
    """One passage of the contract, as something to read and to cite."""

    chunk_id: int
    section: str = ""
    breadcrumb: str = ""
    page_display: str = ""
    text: str


class Passages(BaseModel):
    """`search_contract`: what the contract says, and nothing about what it means.

    An empty list is an answer. `note` says so in the words the host should use,
    because the failure this guards against is a model that finds nothing,
    reaches for what it knows about contracts in general, and presents it as
    what *this* contract says.
    """

    document_id: int
    query: str
    mode: str = ""
    passages: list[Passage] = Field(default_factory=list)
    note: str = ""


# --------------------------------------------------------------------------
# API JSON -> the models above
# --------------------------------------------------------------------------


def started(health: dict[str, Any], *, api_url: str, criteria: int, key_configured: bool,
            ) -> Started:
    return Started(
        api_url=api_url,
        version=str(health.get("version", "")),
        key_present=bool(health.get("key_present")),
        auth_required=bool(health.get("auth_required")),
        key_configured=key_configured,
        analysis_model=str(health.get("analysis_model", "")),
        retrieval_mode=str(health.get("retrieval_mode", "")),
        documents=int(health.get("documents", 0)),
        analyses_running=int(health.get("analyses_running", 0)),
        criteria=criteria,
        next_step=_next_step(health),
    )


def _next_step(health: dict[str, Any]) -> str:
    """What to do, given what is true. Ordered by what blocks what."""
    if not health.get("key_present"):
        return (
            "ANTHROPIC_API_KEY is not set on the analyzer, so compliance analysis will be "
            "refused. Tell the user; upload_contract and search_contract still work."
        )
    if not health.get("documents"):
        return "There are no contracts yet. Call upload_contract with a path or a url."
    return (
        "Call list_contracts to get a document_id, then analyze_compliance for the five "
        "criteria or search_contract for anything else."
    )


def criterion(payload: dict[str, Any]) -> Criterion:
    return Criterion(
        id=payload["id"],
        requirement=payload.get("requirement", ""),
        question=payload.get("question", ""),
        sub_requirements=[
            SubRequirement(id=s["id"], requirement=s.get("requirement", ""))
            for s in payload.get("sub_requirements", [])
        ],
        states=list(payload.get("states", [])),
    )


def contract(payload: dict[str, Any]) -> Contract:
    last = payload.get("last_analysis")
    return Contract(
        document_id=payload["document_id"],
        filename=payload.get("filename", ""),
        pages=payload.get("pages"),
        chunks=payload.get("chunks", 0),
        ingested_at=payload.get("ingested_at", ""),
        last_analysis=None if not last else LastAnalysis(
            analysis_id=last["analysis_id"],
            status=last.get("status", ""),
            completed_at=last.get("completed_at"),
            states=dict(last.get("states") or {}),
            needs_review=last.get("needs_review", 0),
        ),
    )


def uploaded(payload: dict[str, Any]) -> Uploaded:
    return Uploaded(
        document_id=payload["document_id"],
        filename=payload.get("filename", ""),
        pages=payload.get("pages"),
        chunks=payload.get("chunks", 0),
        elapsed_s=payload.get("elapsed_s", 0.0),
        note=(
            "Use this document_id for every later call about this contract. A second "
            "upload of the same file would get a different id and would not share this "
            "one's analyses."
        ),
    )


def analysis_started(payload: dict[str, Any], *, poll_after: float) -> AnalysisStarted:
    criteria = [c["id"] for c in payload.get("criteria", [])]
    return AnalysisStarted(
        analysis_id=payload["analysis_id"],
        document_id=payload["document_id"],
        status=payload.get("status", "queued"),
        criteria=criteria,
        poll_after_seconds=poll_after,
        next_step=(
            f"The run takes about a minute. Wait {poll_after:.0f} seconds, then call "
            "get_analysis with this analysis_id; keep polling while it returns "
            "retry_after_seconds."
        ),
    )


def analysis_state(payload: dict[str, Any], *, poll_after: float, detail: str) -> AnalysisState:
    """`GET /analyses/{id}` -- live job or stored row -- as the host reads it."""
    report = payload.get("report") or {}
    totals = report.get("totals") or {}
    progress = payload.get("progress") or {}
    status = payload.get("status", "")
    finished = status in TERMINAL
    results = report.get("results") or []
    return AnalysisState(
        analysis_id=payload["analysis_id"],
        document_id=payload["document_id"],
        status=status,
        stage=payload.get("stage", ""),
        done=progress.get("done", 0),
        total=progress.get("total", 0),
        criteria=[
            CriterionProgress(
                id=c["id"],
                status=c.get("status", "queued"),
                state=c.get("state"),
                confidence=c.get("confidence"),
                needs_review=c.get("needs_review"),
            )
            for c in payload.get("criteria", [])
        ],
        states=_states(results),
        needs_review=totals.get("needs_review", 0),
        mean_confidence=totals.get("mean_confidence", 0.0),
        cost_usd=totals.get("cost_usd", 0.0),
        latency_s=totals.get("latency_s", 0.0),
        verdicts=[_verdict(r, detail=detail) for r in results],
        skipped=list(report.get("skipped") or []),
        error=payload.get("error"),
        trace_id=payload.get("trace_id"),
        retry_after_seconds=None if finished else poll_after,
        next_step=_analysis_next_step(status, detail, poll_after),
    )


def _states(results: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for result in results:
        state = result.get("compliance_state")
        if state:
            counts[state] = counts.get(state, 0) + 1
    return counts


def _verdict(result: dict[str, Any], *, detail: str) -> Verdict:
    full = detail == "full"
    return Verdict(
        criterion_id=result.get("criterion_id", ""),
        question=result.get("compliance_question", ""),
        state=result.get("compliance_state", ""),
        confidence=result.get("confidence", 0.0),
        needs_review=bool(result.get("needs_review")),
        sub_requirements={
            s["id"]: s.get("status", "") for s in result.get("sub_requirements", [])
        },
        # `?detail=summary` already empties both on the API side; this is what
        # makes that visible here rather than looking like data that went
        # missing.
        rationale=result.get("rationale", "") if full else "",
        quotes=[
            Quote(
                text=q.get("text", ""),
                section_ref=q.get("section_ref", ""),
                page_display=q.get("page_display", ""),
                chunk_id=q.get("chunk_id"),
                verified=bool(q.get("verified", True)),
            )
            for q in (result.get("relevant_quotes") or [])
        ] if full else [],
    )


def _analysis_next_step(status: str, detail: str, poll_after: float) -> str:
    if status not in TERMINAL:
        return (
            f"Not finished. Wait {poll_after:.0f} seconds and call get_analysis again with "
            "the same analysis_id."
        )
    if status == "interrupted":
        return "The process running this analysis went away. Start it again with " \
               "analyze_compliance."
    if status == "failed":
        return "This run failed. Read `error`, and start a new one if it is fixable."
    if detail == "summary":
        return (
            "Finished. Report the states and confidences as they are. Call get_analysis "
            'with detail="full" only if the user asks for the quotes or the reasoning.'
        )
    return "Finished. Every quote is the contract's own words; do not paraphrase one as a quote."


def passages(payload: dict[str, Any]) -> Passages:
    found = payload.get("passages") or []
    return Passages(
        document_id=payload["document_id"],
        query=payload.get("query", ""),
        mode=payload.get("mode", ""),
        passages=[
            Passage(
                chunk_id=p["chunk_id"],
                section=p.get("section", ""),
                breadcrumb=p.get("breadcrumb", ""),
                page_display=p.get("page_display", ""),
                text=p.get("text", ""),
            )
            for p in found
        ],
        note=(
            "Answer only from these passages, and cite the section each claim came from."
            if found else
            "Nothing in this contract matched. Say that the contract does not appear to "
            "cover it rather than answering from general knowledge."
        ),
    )


Detail = Literal["summary", "full"]

__all__ = [
    "TERMINAL",
    "AnalysisStarted",
    "AnalysisState",
    "Contract",
    "Criterion",
    "CriterionProgress",
    "Detail",
    "LastAnalysis",
    "Passage",
    "Passages",
    "Quote",
    "Started",
    "SubRequirement",
    "Uploaded",
    "Verdict",
    "analysis_started",
    "analysis_state",
    "contract",
    "criterion",
    "passages",
    "started",
    "uploaded",
]
