"""The MCP server: a data plane over the same API the browser uses.

The host -- Claude Desktop, Copilot, any MCP client -- is already an agent with
a model, a transcript and a user in front of it. So this server does not try to
be a second one. It publishes **ids, jobs and passages**, and the division of
labour it enforces is the only interesting decision in the file:

| Job | Generated by | The tool |
|---|---|---|
| The five criteria | **our** pipeline | `analyze_compliance`, then `get_analysis` |
| Any other question | the **host's** model | `search_contract` -- passages only |
| Conversation | the host | no tool at all |

**Analyze; do not let the host score compliance.** A host handed passages and
asked to fill in the five criteria will produce something that reads like a
compliance report and is not one: quotes it composed rather than extracted,
no evaluator pass, no confidence, no `analysis_id`, and nothing in the logs or
the KPI table to say it ever happened. Analysis is a 60-180 s job with a schema
and a validator, so it stays a job with a schema and a validator, and the tool
returns a handle to it.

**Retrieve; do not wrap chat.** `POST /api/chat` is the UI's endpoint: it runs
an evidence ledger, verifies each citation against the passage it came from,
streams, and answers `no_context` when the ledger is empty. Exposed as a tool
it would become the host paying a second model to answer a question it was
already going to answer, with `history` it must serialise and replay, and with
the streaming dropped. `search_contract` gives it the passages instead, and the
host keeps the transcript it already owns. `ask_contract` and `search_contract`
are deliberately not both registered: a host given two ways to ask a question
picks one at random.

**There is no session.** `document_id` and `analysis_id` are the entire state,
exactly as they are for the browser and for a connector -- see `docs/api.md`.
This process holds a connection pool and nothing else: no database, no
transcript, no "current document". That is what lets a host reconnect, call
`list_contracts`, and carry on.

Everything reaches the API over HTTP (`client.py`). Nothing here opens SQLite,
embeds anything, or calls a model.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Annotated

from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from pydantic import Field

from . import schemas
from .client import ApiClient, ApiFailure
from .config import ConnectorSettings, get_settings

log = logging.getLogger("mcp_connector")

NAME = "contract-analyzer"
VERSION = "0.1.0"

#: Sent once, at connect time, before any tool is called. Tools describe
#: themselves; this describes the *protocol* -- the order to call them in, and
#: the two rules that keep the host from inventing a compliance report or a
#: clause. A host that reads only this and the tool names should still do the
#: right thing.
INSTRUCTIONS = """\
Contract Analyzer: compliance analysis of PDF contracts, and retrieval over them.

1. Call `get_started` first. If `key_present` is false, tell the user compliance
   analysis is unavailable and do not start one.
2. If you have no `document_id`, call `list_contracts`, or `upload_contract`
   with a local path or a URL.
3. "Is this contract compliant?", or anything about the five criteria, is
   `analyze_compliance` followed by polling `get_analysis`. It takes about a
   minute. Do not answer those five questions yourself from passages: the
   verdicts, the confidences and the verified quotes come from the analysis
   pipeline, and a report you compose is not one this system can stand behind.
   Keep `detail="summary"` unless the user asks for quotes or reasoning.
4. Any other question about a contract is `search_contract(document_id, query)`.
   Answer only from the passages it returns, and cite the section each claim
   came from. If it returns nothing, say the contract does not appear to cover
   it -- do not fall back to what contracts usually say.
5. This server keeps no session. Pass `document_id` or `analysis_id` on every
   call. Each upload mints a new id, even for the same file.
"""


def build_server(settings: ConnectorSettings, api: ApiClient) -> FastMCP:
    """The server, with its tools bound to one API client.

    A factory rather than a module-level singleton so the tests can drive the
    whole tool surface over a mock transport, in-process, with no network and
    no key -- the same seam `create_app(settings, embedder=..., client=...)`
    gives the API's tests.

    The tools are nested rather than free functions for the same reason: the
    client they use is an argument, not a global that has to be monkeypatched.
    """
    mcp = FastMCP(name=NAME, version=VERSION, instructions=INSTRUCTIONS)

    def call(method: str, path: str, **kwargs) -> object:
        """Every tool's one line of I/O, with the error contract applied.

        `ApiFailure` becomes `ToolError`, which FastMCP returns as an MCP error
        result with the message intact. The message is `code: message hint` --
        `document_not_found: No document with id 7. Pick a contract from the
        library, or upload one` -- because a host recovers from that and cannot
        recover from a traceback or from "500".
        """
        try:
            return api.call(method, path, **kwargs)
        except ApiFailure as exc:
            log.info("mcp.tool_failed", extra={"path": path, "code": exc.code})
            raise ToolError(str(exc)) from None

    # -- orientation -------------------------------------------------------

    @mcp.tool(annotations={"readOnlyHint": True, "openWorldHint": False})
    def get_started() -> schemas.Started:
        """Check what this Contract Analyzer can do right now, and what to call next.

        Call this before anything else in a conversation. It reports live state,
        not documentation: whether an answer key is configured (without one,
        compliance analysis is refused), whether the API requires a key this
        connector may not have, how many contracts are stored, and how many
        analyses are already running.
        """
        health = call("GET", "/health")
        criteria = call("GET", "/criteria")
        assert isinstance(health, dict) and isinstance(criteria, list)
        return schemas.started(
            health,
            api_url=settings.api_url,
            criteria=len(criteria),
            key_configured=bool(settings.api_key_value),
        )

    @mcp.tool(annotations={"readOnlyHint": True, "openWorldHint": False})
    def list_criteria() -> list[schemas.Criterion]:
        """The five compliance criteria this service analyses, with their sub-requirements.

        Use it to answer "what do you check?", and to pick `criterion_ids` for a
        partial run. The sub-requirements are the parts a verdict is built from:
        a contract is Partially Compliant because some of them are met and some
        are not, and naming them is how you explain a verdict rather than assert it.
        """
        payload = call("GET", "/criteria")
        assert isinstance(payload, list)
        return [schemas.criterion(item) for item in payload]

    # -- contracts ---------------------------------------------------------

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False,
                           "idempotentHint": False, "openWorldHint": True})
    def upload_contract(
        path: Annotated[
            str | None,
            Field(description="Absolute path to a PDF on the machine running this "
                              "connector. Only available over the stdio transport."),
        ] = None,
        url: Annotated[
            str | None,
            Field(description="A public https link to the PDF. The connector downloads "
                              "it and uploads it to the API."),
        ] = None,
    ) -> schemas.Uploaded:
        """Add a PDF contract and index it, returning the `document_id` everything else needs.

        Give exactly one of `path` or `url`. Parsing, chunking and embedding the
        contract happen before this returns, so a long contract takes a few tens
        of seconds.

        **Every upload mints a new `document_id`, even for identical bytes.**
        Two sessions working on the same contract get different ids and cannot
        see each other's analyses. Never reuse an id from an earlier
        conversation -- call `list_contracts` instead.

        There is no way to pass the file's bytes directly: base64 in a tool
        argument costs a third more than the file and is re-sent on every retry.
        A person can also upload through the web UI, after which `list_contracts`
        will show it.
        """
        if (path is None) == (url is None):
            raise ToolError(
                "validation: give exactly one of `path` (a local file) or `url` "
                "(a link the connector can download)."
            )
        if url is not None:
            try:
                filename, body = api.fetch_pdf(url)
            except ApiFailure as exc:
                raise ToolError(str(exc)) from None
        else:
            filename, body = _read_local_pdf(str(path), settings)

        payload = call(
            "POST",
            "/documents",
            files={"file": (filename, body, "application/pdf")},
            timeout=settings.mcp_upload_timeout_seconds,
        )
        assert isinstance(payload, dict)
        return schemas.uploaded(payload)

    @mcp.tool(annotations={"readOnlyHint": True, "openWorldHint": False})
    def list_contracts() -> list[schemas.Contract]:
        """Every contract stored on this service, newest first, with its last analysis.

        This is how you recover a `document_id` -- after a reconnect, or when the
        user uploaded through the web UI rather than through you. `last_analysis`
        says whether a contract has already been analysed and how it came out, so
        you can offer to read that instead of starting a run that costs a minute
        and real money.
        """
        payload = call("GET", "/documents")
        assert isinstance(payload, list)
        return [schemas.contract(item) for item in payload]

    # -- the five criteria -------------------------------------------------

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False,
                           "idempotentHint": False, "openWorldHint": False})
    def analyze_compliance(
        document_id: Annotated[int, Field(description="From upload_contract or list_contracts.")],
        criterion_ids: Annotated[
            list[str] | None,
            Field(description="Criterion ids from list_criteria. Omit to run all five."),
        ] = None,
    ) -> schemas.AnalysisStarted:
        """Start the compliance analysis of one contract. Returns immediately with an id.

        **This starts a job; it does not answer.** The run takes 60-180 seconds
        and costs real money. Poll `get_analysis` with the `analysis_id` this
        returns, waiting `poll_after_seconds` between calls.

        Use this -- never your own reading of retrieved passages -- for the five
        criteria. The verdicts come from an agent per criterion with a structured,
        validated output and quotes checked back against the passages they were
        taken from, and the run is recorded with an id that appears in the logs
        and the KPI table. A summary you write from `search_contract` results has
        none of that and is indistinguishable from one that does until someone
        checks a quote.

        Submitting again while a run with the same criteria is in flight returns
        that run rather than starting a second one.
        """
        payload = call(
            "POST",
            "/analyses",
            json={"document_id": document_id, "criteria": criterion_ids},
            # What makes the KPI page able to say how much of this deployment's
            # use comes through MCP. See DECLARABLE_SURFACES in the API.
            headers={"X-Surface": "mcp"},
        )
        assert isinstance(payload, dict)
        return schemas.analysis_started(payload, poll_after=settings.mcp_poll_seconds)

    @mcp.tool(annotations={"readOnlyHint": True, "openWorldHint": False})
    def get_analysis(
        analysis_id: Annotated[str, Field(description="From analyze_compliance.")],
        detail: Annotated[
            schemas.Detail,
            Field(description="`summary` for states and confidences; `full` adds the "
                              "quotes and the reasoning."),
        ] = "summary",
    ) -> schemas.AnalysisState:
        """Check an analysis, and read its verdicts once it has them.

        While the run is unfinished this returns `retry_after_seconds`; wait that
        long and call again. When it is finished the field is null and `verdicts`
        holds one entry per criterion.

        Keep `detail="summary"` -- the states, confidences and review flags -- for
        anything you are going to summarise. Ask for `"full"` only when the user
        wants the evidence: it adds every quote and every rationale, which is a
        great deal of text to carry in a conversation that then continues.

        The quotes in a full report are the contract's own words, checked back
        against the passage they came from. Present them as quotes; present
        anything you write yourself as your own words.
        """
        payload = call("GET", f"/analyses/{analysis_id}", params={"detail": detail})
        assert isinstance(payload, dict)
        return schemas.analysis_state(
            payload, poll_after=settings.mcp_poll_seconds, detail=detail
        )

    # -- everything else about the contract --------------------------------

    @mcp.tool(annotations={"readOnlyHint": True, "openWorldHint": False})
    def search_contract(
        document_id: Annotated[int, Field(description="The contract to search. Required: "
                                                      "results can never come from another.")],
        query: Annotated[str, Field(description="What to look for, in the question's own "
                                                "words. Both meaning and wording are matched.")],
    ) -> schemas.Passages:
        """Find passages of one contract. Use this for every question except the five criteria.

        Returns ranked passages with their section, page and chunk id -- the
        contract's text, with nothing generated on top of it. Answer from these
        passages and cite the section each claim came from.

        **If it returns nothing, the contract does not appear to cover it.** Say
        that. Falling back to what contracts usually say is the one failure this
        tool exists to prevent, and the user cannot tell the difference.

        Ask more than once with different wording when a first search misses:
        contracts name the same obligation in several ways ("bastion host",
        "secure administrative pathway"), and retrieval matches both the words
        and the meaning.
        """
        payload = call(
            "POST",
            f"/documents/{document_id}/search",
            json={"query": query, "top_k": settings.mcp_search_top_k},
        )
        assert isinstance(payload, dict)
        return schemas.passages(payload)

    return mcp


def _read_local_pdf(raw: str, settings: ConnectorSettings) -> tuple[str, bytes]:
    """A PDF from this machine's filesystem, for the stdio transport only.

    **`path` is refused over HTTP.** A tool argument is a string a model chose,
    and "read this file and send it somewhere" is a file-read primitive: over
    stdio the server is a subprocess the user launched, running as them, reading
    a file they could have opened anyway; over HTTP it is a service that would
    read *its own* filesystem -- inside a container, where the host's paths mean
    something else entirely, and on behalf of whoever can reach the port.

    `MCP_UPLOAD_ROOT` narrows it further where even that is too much: set it and
    only files under that directory are accepted.
    """
    if settings.mcp_transport != "stdio":
        raise ToolError(
            "path_not_allowed: this connector is serving HTTP, where `path` would read "
            "the server's own filesystem rather than yours. Pass `url` instead, or have "
            "the user upload the contract through the web UI and call list_contracts."
        )
    path = Path(raw).expanduser()
    if not path.is_absolute():
        raise ToolError(
            f"validation: {raw!r} is not an absolute path. The connector has no working "
            "directory a relative path could be resolved against."
        )
    path = path.resolve()
    root = settings.mcp_upload_root
    if root is not None and not path.is_relative_to(root.resolve()):
        raise ToolError(
            f"path_not_allowed: this connector only reads contracts under {root}. "
            "Move the file there, or pass a url."
        )
    if not path.is_file():
        raise ToolError(f"not_found: there is no file at {path}.")
    if path.suffix.lower() != ".pdf":
        raise ToolError(
            f"not_a_pdf: {path.name} is not a PDF. This service analyses PDF contracts."
        )
    return path.name, path.read_bytes()


def configure_logging(level: str = "INFO") -> None:
    """Logs to stderr, always.

    On the stdio transport stdout *is* the JSON-RPC stream. One line written to
    it -- a log record, a warning, a stray print -- and the host sees a protocol
    error instead of a tool result. This is the whole reason the function exists
    rather than a `basicConfig` call somewhere convenient.
    """
    logging.basicConfig(
        stream=sys.stderr,
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )


def main(argv: list[str] | None = None) -> int:
    """Run the server. `stdio` by default; `http` for a container or a shared one."""
    parser = argparse.ArgumentParser(
        prog="python -m mcp_connector",
        description="MCP server for the Contract Analyzer API.",
    )
    parser.add_argument("--transport", choices=("stdio", "http"), default=None,
                        help="Overrides MCP_TRANSPORT.")
    parser.add_argument("--host", default=None, help="HTTP only. Overrides MCP_HOST.")
    parser.add_argument("--port", type=int, default=None, help="HTTP only. Overrides MCP_PORT.")
    parser.add_argument("--api-url", default=None, help="Overrides CA_API_URL.")
    args = parser.parse_args(argv)

    overrides = {
        key: value
        for key, value in (
            ("mcp_transport", args.transport),
            ("mcp_host", args.host),
            ("mcp_port", args.port),
            ("ca_api_url", args.api_url),
        )
        if value is not None
    }
    settings = get_settings(**overrides)
    configure_logging()

    with ApiClient(settings) as api:
        server = build_server(settings, api)
        log.info(
            "mcp.startup api_url=%s transport=%s", settings.api_url, settings.mcp_transport
        )
        if settings.mcp_transport == "http":
            server.run(transport="http", host=settings.mcp_host, port=settings.mcp_port)
        else:
            # No banner on stdio: it is noise in a desktop client's log, and the
            # startup line above already says what a reader needs.
            server.run(transport="stdio", show_banner=False)
    return 0


if __name__ == "__main__":  # `python -m mcp_connector.server`, which entrypoint.sh runs
    raise SystemExit(main())
